// css
import CartMobileIcon from "./components/CartMobileIcon";
import Nav from "./components/Nav";
import CartProvider from "./context/CartContext";

import "./globals.css";
import { Inter, Bangers, Quicksand, Roboto_Condensed } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

const quicksand = Quicksand({
  subsets: ["latin"],
  variable: "--font-quicksand"
});

const bangers = Bangers({
  subsets: ["latin"],
  variable: "--font-bangers",
  weight: ["400"]
});

const RobotoCondensed = Roboto_Condensed({
  subsets: ["latin"],
  variable: "--font-robotoCondensed",
  weight: ["400", "400", "700"]
});

export const metadata = {
  title: "PizzaHub ",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <CartProvider>
      <html lang="en">
        <body
          className={`${quicksand.variable} ${bangers.variable} ${RobotoCondensed.variable} font-quicksand`}
        >
          <Nav />
          <CartMobileIcon /> {children}
        </body>
      </html>
    </CartProvider>
  );
}
